shannon_gmo:
  strategy: shannon
  symbol:
    base: BTC
    quote: JPY
    settlement: JPY
    type: spot
    exc: gmo
  virtual_amount:
    base: 0.1143      # 0.0381*3
    quote: 425124     # 141708*3
crawler_coincheck:
  strategy: crawler
  symbol:
    base: BTC
    quote: JPY
    settlement: JPY
    type: spot
    exc: coincheck
  kline_builder: []
crawler_bitflyer:
  strategy: crawler
  symbol:
    base: BTC
    quote: JPY
    settlement: JPY
    type: perp
    exc: bitflyer
  kline_builder:
    - timeframe_sec: 150
      len: 300
crawler_bitflyer_spot:
  strategy: crawler
  symbol:
    base: BTC
    quote: JPY
    settlement: JPY
    type: spot
    exc: bitflyer
  kline_builder:
    - timeframe_sec: 150
      len: 300
crawler_binance_btcusdt_spot:
  strategy: crawler
  symbol:
    base: BTC
    quote: USDT
    settlement: USDT
    type: spot
    exc: binance
  kline_builder:
    - timeframe_sec: 150
      len: 300
