shannon_gmo:
  strategy: shannon
  symbol:
    base: BTC
    quote: JPY
    settlement: JPY
    type: spot
    exc: gmo
  virtual_amount:
    base: 0.1143      # 0.0381*3
    quote: 425124     # 141708*3
abcdf_tachibana:
  strategy: abcdf
  symbol:
    base: "9432"
    quote: JPY
    settlement: JPY
    type: margin
    exc: tachibana
  ref_symbols:
    - "7203"
    - "6758"
    - "9432"
  model_path: model.zstd
